#! /bin/sh

# FlowerFetch, based on mfetch by depsterr: https://github.com/depsterr/mfetch

# Get user 
user="${USER-$(id -u -n)}"

# Get host 
host="$(uname -n)"

# Get OS
. /etc/os-release # load lib
os="$PRETTY_NAME"

term="st"

# Shell
shell="${SHELL##*/}"

# Here you can write your wm or de
wm="i3"

#####################
# Colors and palette 
#####################

# Colors and palette method stolen from dylanaraps pftech: https://github.com/dylanaraps/pfetch
c0='[0m'
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'

palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"
	 
ARTR1="${c0}  \    /\    "
ARTR2="${c0}   )  ( ')   "
ARTR3="${c0}  (  /  )    "
ARTR4="${c0}   \(__)|    "

# Print
cat <<-EOF



 ${ARTR1}${c3}${user}${c0} in ${c0}${host}
 ${ARTR2}${c3}shell${c0}  ${shell}
 ${ARTR3}${c3}wm${c0}     ${wm}
 ${ARTR4}${c3}term${c0}   ${term}
        
             ${palette}


EOF
