#!/bin/sh
# From https://github.com/LukeSmithxyz/voidrice
# Dmenu Script for a "Emoji Keyboard" and copy

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/txt/emoji | dmenu -i -l 3 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

echo "$chosen" | tr -d '\n' | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard." &
