#!/bin/sh
# From https://github.com/LukeSmithxyz/voidrice 
# Dmenu Script for binary prompts

# Usage
# `./prm "Do you want to shutdown?" "shutdown -h now"`

[ "$(printf "No\\nYes" | dmenu -i -p "$1" )" = "Yes" ] && $2
