#!/bin/bash
# From https://gitlab.com/dwt1/dotfiles/-/tree/master/.dmenu
# Dmenu script for quick bookmarked files

# Here you can declare the options of your files
declare options=("i3
Barsystem
Barworkspace
Alacritty
Dunst
Picom
st
zsh
dmenu
quit")

# Call Dmenu
choice=$(echo -e "${options[@]}" | dmenu -i -p 'Open config file: ')

# The choices and the path of each file
case "$choice" in
	quit)
		echo "Program terminated." && exit 1
	;;
	Alacritty)
		choice="$HOME/.config/alacritty/alacritty.yml"
	;;
	Dunst)
		choice="$HOME/.config/dunst/dunstrc"
	;;
	i3)
		choice="$HOME/.config/i3/config"
	;;
	Neovim)
		choice="$HOME/.config/nvim/init.vim"
	;;
	Barsystem)
		choice="$HOME/.config/polybar/system.ini"
	;;
	Barworkspace)
		choice="$HOME/.config/polybar/workspace.ini"
	;;
	Picom)
		choice="$HOME/.config/picom/picom.conf"
	;;
	st)
		choice="$HOME/Workspace/Personal/St/config.h"
	;;
	dmenu)
		choice="$HOME/Workspace/Personal/Dmenu/config.h"
	;;
	zsh)
		choice="$HOME/.zshrc"
	;;
	*)
		exit 1
	;;
esac
#Call terminal emulator and open the file
alacritty -e nvim $choice