#!/bin/bash
# From https://gitlab.com/dwt1/dotfiles/-/tree/master/.dmenu
# Dmenu script for quick bookmarked files

# Here you can declare the options of your files
declare options=("alacritty
dunst
i3
neovim
picom
polybar
st
zsh
quit")

# Call Dmenu
choice=$(echo -e "${options[@]}" | dmenu -i -p 'Open config file: ')

# The choices and the path of each file
case "$choice" in
	quit)
		echo "Program terminated." && exit 1
	;;
	alacritty)
		choice="$HOME/.config/alacritty/alacritty.yml"
	;;
	dunst)
		choice="$HOME/.config/dunst/dunstrc"
	;;
	i3)
		choice="$HOME/.config/i3/config"
	;;
	neovim)
		choice="$HOME/.config/nvim/init.vim"
	;;
	picom)
		choice="$HOME/.config/picom/picom.conf"
	;;
	polybar)
		choice="$HOME/.config/polybar/config.ini"
	;;
	st)
		choice="$HOME/Public/Personal/SimplierTerminal/config.h"
	;;
	zsh)
		choice="$HOME/.zshrc"
	;;
	*)
		exit 1
	;;
esac
#Call terminal emulator and open the file
alacritty -e nvim $choice

